# Generated by Django 5.0.3 on 2024-05-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='DRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Délégation Regionale',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='DDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nom')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionadmin.dregion')),
            ],
            options={
                'verbose_name': 'Délégation Departementale',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('BP', models.CharField(blank=True, max_length=64, null=True, verbose_name='BP')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='email')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionadmin.departement', verbose_name='Departement')),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionadmin.cycle')),
                ('departement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionadmin.departement')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
            },
        ),
        migrations.CreateModel(
            name='BesoinEffectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEffectif', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nom')),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionadmin.etablissement')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionadmin.filiere')),
            ],
            options={
                'verbose_name': "Besoin d'effectif",
                'verbose_name_plural': "Besoin d'effectifs",
            },
        ),
    ]
