# Generated by Django 5.0.3 on 2024-05-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionadmin.departement'),
        ),
    ]
