# Generated by Django 5.0.3 on 2024-05-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0002_alter_filiere_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoineffectif',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionadmin.etablissement'),
        ),
    ]
