# Generated by Django 5.0.3 on 2024-05-17 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0004_etudiant_alter_besoineffectif_nombreeffectif_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ddepartement',
            options={'verbose_name': 'Délégation Départementale', 'verbose_name_plural': 'Délégations Départementale'},
        ),
        migrations.AlterModelOptions(
            name='dregion',
            options={'verbose_name': 'Délégation Régionale', 'verbose_name_plural': 'Délégations Régionale'},
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionadmin.ddepartement', verbose_name='Departement'),
        ),
    ]
