# Generated by Django 5.0.3 on 2024-05-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletudiant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=64, null=True, verbose_name='Sexe'),
        ),
    ]
