# Generated by Django 5.0.3 on 2024-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0013_choix'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletudiant',
            name='is_visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
