# Generated by Django 5.0.3 on 2024-06-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0015_profiletudiant_anneemariage_and_more'),
        ('gestiondelegation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletudiant',
            name='regionRegroupement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondelegation.dregion', verbose_name='Region regroupement'),
        ),
        migrations.AlterField(
            model_name='profiletudiant',
            name='estEffectif',
            field=models.BooleanField(blank=True, null=True, verbose_name='Prise effective Mari valide ?'),
        ),
    ]
